pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:3355.v388858a_47b_33-20
  - name: checkov
    image: bridgecrew/checkov:latest
    command: ['cat']
    tty: true
  - name: tflint
    image: ghcr.io/terraform-linters/tflint:latest
    command: ['cat']
    tty: true
"""
        }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh 'ls -R'
            }
        }
        stage('Security Scan') {
           steps {
               container('checkov') {
                   sh 'checkov -d infrastructure/terraform/test'
        }
    }
}
        stage('Lint Infrastructure') {
            steps {
                container('tflint') {
                    sh 'tflint --init'
                    sh 'tflint'
                }
            }
        }
    }

post {
        failure {
            script {
                withCredentials([string(credentialsId: 'slack-webhook-url', variable: 'SLACK_URL')]) {
                    sh 'curl -X POST -H "Content-type: application/json" --data \'{"text":"🚨 *Fallo en Pipeline:* ${env.JOB_NAME} #${env.BUILD_NUMBER}. Revisa: ${env.BUILD_URL}"}\' $SLACK_URL'
                }
            }
        }
        success {
            script {
                withCredentials([string(credentialsId: 'slack-webhook-url', variable: 'SLACK_URL')]) {
                    sh 'curl -X POST -H "Content-type: application/json" --data \'{"text":"✅ *Pipeline Exitoso:* ${env.JOB_NAME} #${env.BUILD_NUMBER}."}\' $SLACK_URL'
                }
            }
        }
    }
}
