pipeline {
    agent { 
        // ... (tu configuración de agente) ...
    }
    stages {
        // ... (tus stages) ...
    }
    post {
        failure {
            script {
                withCredentials([string(credentialsId: 'slack-webhook-url', variable: 'SLACK_URL')]) {
                    def msg = "🚨 *Fallo en Pipeline* | Job: ${env.JOB_NAME} | Build: #${env.BUILD_NUMBER}\n🔗 <${env.BUILD_URL}|Ver detalles en Jenkins>"
                    sh "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"${msg}\"}' \$SLACK_URL"
                }
            }
        }
        success {
            script {
                withCredentials([string(credentialsId: 'slack-webhook-url', variable: 'SLACK_URL')]) {
                    def msg = "✅ *Pipeline Exitoso* | Job: ${env.JOB_NAME} | Build: #${env.BUILD_NUMBER}\n🔗 <${env.BUILD_URL}|Ver reporte completo>"
                    sh "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"${msg}\"}' \$SLACK_URL"
                }
            }
        }
    } // <-- Esta llave cierra el post
} // <-- Esta llave cierra el pipeline (¡Asegúrate de que esta exista!)
